### PR TITLE
fixes and updates

### PR DESCRIPTION
**Pull request by grrtrr**
Thank you for this really useful tool. It is so powerful.

While working on templates, I ran into limitations, please find attached
* when printing error messages, add a newline (`\n`),
* allow the user to also add the `.yaml` `.tmpl` suffixes to files, without breaking existing usage,
* allow to run the same template on multiple `.yaml` inputs,
* allow to run multiple templates on on the same `.yaml` input,
* fix some problems with the html/text template parser.

### CODE REVIEW

**Comment by suntong** [comment]
Thanks a lot for the PR. They look great and will greatly improve the functionality. 
Would you add some more test cases please (especially to cover the accepting of filenames & multiple inputs/templates cases)? 

Thanks again!

**Comment by grrtrr** [comment]
@suntong - thank you for reviewing this. Yes, of course, I will look into adding test cases.

I realize this is quite a lot in one PR, it evolved while I was using it to generate `enum` definitions for multiple languages.

Would you like me to split this into multiple smaller requests?

Thanks again.

**Comment by suntong** [comment]
> Would you like me to split this into multiple smaller requests?

Hmm..., I'm OK. Keep going, but up to you -- I actually don't see why or why not, :-)

**Comment by grrtrr** [comment]
Thank you -- I will follow up with the test cases shortly, I don't have the files with me. Will likely be tomorrow.

**Comment by grrtrr** [comment]
Please find tests attached as requested, let me know any comments. I am nearly done working on enum generation for `.go`, from the same input files, to generate fmt.Stringer and json.(Un)marshaler functions.

**Comment by suntong** [comment]
Perfect!

> I am nearly done working on enum generation...

Would you prefer me merging now, or wait a bit in case you have some small fixes that might happen?

**Comment by grrtrr** [comment]
Thank you -- please feel free to go ahead; I am using easygen for my own testing here.

I do have enum generation for go with fmt.Stringer, json.Marshaler/Unmarshaler, and yaml.Marshaler; I can send this separately.

**Comment by suntong** [comment]
I'll fix the readme tonight.

**Comment by suntong** [comment]
Hmm, travis tested OK but codeship test failed:

https://app.codeship.com/projects/135255/builds/25398797?pipeline=3bdc05b2-d44f-4ae2-a631-4ad56ebd7349

Would you take a look please?

**Comment by grrtrr** [comment]
Thank you so much. I will test and polish the `.go` enum template and send it.

**Comment by grrtrr** [comment]
I am looking at it now and will get back shortly.

Quoting suntong:
> Hmm, travis tested OK but codeship test failed:
> 
> https://app.codeship.com/projects/135255/builds/25398797?pipeline=3bdc05b2-d44f-4ae2-a631-4ad56ebd7349
> 
> Would you take a look please? 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/go-easygen/easygen/pull/3#issuecomment-303482694

--

**Comment by grrtrr** [comment]
I am unable to view this page, since I am not the owner of the repository.

I pushed one commit to my clone of easygen: https://github.com/grrtrr/easygen

and watched the the codeship run - it worked. Could this be a timing issue, or
do you know if this was on an earlier commit?

**Comment by grrtrr** [comment]
I think I know a possible reason: there are 2 easygen repositories, one is this one (`go-easygen/easygen`) and (`suntong/easygen`). 

From what I can see, codeship seems to be set up for `suntong/easygen` - that might be a reason.

**Comment by suntong** [comment]
Ahh!!!! Sorry my bad. Thanks for getting to the bottom of it. I'll fix it tonight. 

Thanks again.

**Comment by suntong** [comment]
hmm... So, so, strange. 

I switched my codeship build to `go-easygen/easygen`, but codeship still errors at the same place:

```
=== RUN: ExampleEnumMultipleTemplates
[easygen] Fatal error - template: enum_c-header.tmpl:1: illegal number syntax: "-"
FAIL	github.com/go-easygen/easygen	0.099s
?   	github.com/go-easygen/easygen/cmd/easygen	[no test files]
```

I've put the whole log at https://gist.github.com/suntong/ca137dacaafa5a5dfd7a1bb29029d154, and have found nothing particular suspicious there. Could you double-check for me please? 

I pull the latest code to my local and `go test -v ./...` just run fine at my place as well. 

The only thing I can think of is the go's version that codeship uses, but since it is working for you, that should not be the reason.

So, so, strange... still looking into it further...

**Comment by suntong** [comment]
I add go version check and rebuild again, and got:

    go version go1.4 linux/amd64

How did you make it work for you?

**Comment by suntong** [comment]
Ha, finally I got it working, by referring to 
https://documentation.codeship.com/basic/languages-frameworks/go/#versions-and-setup

**Comment by grrtrr** [comment]
I apologize for the trouble. I had not used Codeship before. Upon inspection I realized that the 'green' in my build was meaningless, as the build log showed only up to "preparing the virtual machine" - it stopped there. 

It had been using the same go version:
```bash
rof@railsonfire_d32c40b5-f8da-49bd-82ad-fb4ab4305cf7_c7cfede51e24:~$ go version
go version go1.4 linux/amd64
```

The templates that I submitted all require at least Go 1.6, since it uses the [trim-whitespace syntax](https://golang.org/doc/go1.6#template) introduced with that release, where
```
{{23 -}}
   <
{{- 45}}
```
formats as `23<45`. Go 1.4 came out at the end of 2014 - close to 3 years ago. Did not know that the defaults are that old.

Thank you for sorting this out.

**Comment by suntong** [comment]
No worry. 

Were you able to see the last successful build log? Else, are you able to trigger another build to see how I did it?

**Comment by grrtrr** [comment]
Yes ... I was able to set it up after looking at how you had configured it :)
image

**Comment by suntong** [comment]
Hi Gerrit, 

I've just added some easygen cli exec testing cases, including allowing the user to also add the .yaml .tmpl suffixes to files (ref: https://github.com/go-easygen/easygen/commit/47e943a84e1da498e6fc2e6cd7e53a94900f225f). 
Would you add more tests that test the rest of your enhancements please?

**Comment by grrtrr** [comment]
These changes look great -- I like the fact that you are comparing via `diff` to the reference files. It is a good testing technique.

Will get back with test cases; it could take a day or two.

**Comment by suntong** [comment]
NP, take your time.

**Pull request merged**
